// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Erc20Transfer struct {
	Timestamp    pgtype.Timestamptz
	Sender       string
	Recipient    string
	Amount       pgtype.Numeric
	TxHash       string
	TokenAddress string
}

type Erc20TransfersSum5Min struct {
	Time         interface{}
	TokenAddress string
	TotalAmount  int64
}
